plugins {
    id 'com.android.application'
}

android {
    namespace 'net.kollnig.breakfast'
    compileSdk = 36

    defaultConfig {
        applicationId "net.kollnig.breakfast"
        minSdk 24
        targetSdk 36
        versionCode 26031702
        versionName "0.0.1"
    }

    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    dependenciesInfo {
        includeInApk = false
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'androidx.browser:browser:1.9.0'
    implementation 'com.google.android.material:material:1.13.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.2.1'
    implementation 'androidx.activity:activity:1.13.0'
    implementation 'androidx.core:core:1.18.0'
    implementation 'androidx.work:work-runtime:2.11.1'
    implementation project(':distractionlib')

    // Networking
    implementation 'com.squareup.okhttp3:okhttp:5.3.2'

    // JSON parsing
    implementation 'com.google.code.gson:gson:2.13.2'
}
